import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b border-black/5 bg-white">
          <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-4">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-black text-white font-semibold">
                AE
              </div>
              <div className="leading-tight">
                <div className="text-sm font-semibold text-black">AECE</div>
                <div className="text-xs text-zinc-500">Ethical Assessment & Explanation</div>
              </div>
            </div>
            <nav className="flex gap-4 text-sm">
              <Link
                href="/dashboard"
                className="text-zinc-700 hover:text-black transition-colors"
              >
                Dashboard
              </Link>
              <Link
                href="/history"
                className="text-zinc-700 hover:text-black transition-colors"
              >
                History
              </Link>
            </nav>
          </div>
        </header>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
